# Catapult batch script for ThreePEScheduler
# Run:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_three_pe_scheduler_catapult.tcl

project new -name three_pe_scheduler

solution new -state initial
solution options defaults
solution options set /Output/GenerateCycleNetlist false

solution file add ./src/stem/stem_config.h        -type C++
solution file add ./src/pe/pe_config.h            -type C++
solution file add ./src/pe/three_pe_rules.h       -type C++
solution file add ./src/pe/three_pe_rules.cpp     -type C++
solution file add ./src/pe/generic_pe.h           -type C++
solution file add ./src/pe/generic_pe.cpp         -type C++
solution file add ./src/pe/three_pe_block.h       -type C++
solution file add ./src/pe/three_pe_block.cpp     -type C++
solution file add ./src/pe/three_pe_scheduler.h   -type C++
solution file add ./src/pe/three_pe_scheduler.cpp -type C++

solution file add ./src/pe/three_pe_scheduler_tb.cpp -type C++ -exclude true

go analyze

if {[catch {directive set -MEM_MAP_THRESHOLD 8192} err]} {
    puts "MEM_MAP_THRESHOLD failed: $err"
} else {
    puts "MEM_MAP_THRESHOLD = 8192"
}

if {[catch {directive set -CLOCK_OVERHEAD 0} err]} {
    puts "CLOCK_OVERHEAD failed: $err"
} else {
    puts "CLOCK_OVERHEAD = 0"
}

go compile

set ccs_fd [open ./three_pe_scheduler.ccs w]
puts $ccs_fd {// Auto-generated by run_three_pe_scheduler_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain three_pe_scheduler*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'three_pe_scheduler*'}
  }
}}
close $ccs_fd

if {![info exists KEEP_GUI_OPEN] || !$KEEP_GUI_OPEN} {
    exit
}
