# Catapult GUI script for BW_CNN_Streaming
# Run example:
#   cd Binary_cnn
#   catapult -gui -file scripts/run_streaming_catapult_gui.tcl

project new -name bin_cnn_streaming

solution new -state initial
solution options defaults
solution options set /Flows/Enable-SCVerify yes
solution options set /Output/GenerateCycleNetlist false

solution file add ./src/streaming/bw_cnn_streaming.h -type C++
solution file add ./src/streaming/bw_cnn_streaming.cpp -type C++
solution file add ./src/streaming/bw_cnn_streaming_tb.cpp -type C++ -exclude true

go analyze
go compile
flow package require /SCVerify

# Write a launcher file for reopening this project quickly.
set ccs_fd [open ./bin_cnn_streaming.ccs w]
puts $ccs_fd {// Auto-generated by run_streaming_catapult_gui.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain bin_cnn_streaming*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'bin_cnn_streaming*'}
  }
}}
close $ccs_fd

# NOTE: no 'exit' so GUI stays open
