# Catapult batch script for StemProcessor V2 (tile-optimized)
# Run example:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_stem_v2_catapult.tcl

project new -name stem_v2_processor

# Start from a clean solution state
solution new -state initial
solution options defaults

# Useful default flow options
solution options set /Flows/Enable-SCVerify yes
solution options set /Output/GenerateCycleNetlist false

# Design + testbench files
solution file add ./src/stem_v2/stem_v2_processor.cpp -type C++
solution file add ./src/stem_v2/stem_v2_processor_tb.cpp -type C++ -exclude true

# Analyze
go analyze

# ============================================================================
# Discover Design Hierarchy
# ============================================================================
puts "======== DESIGN HIERARCHY ========"
puts "Top-level children:"
foreach child [solution design get -child /] {
    puts "  $child"
    catch {
        foreach grandchild [solution design get -child $child] {
            puts "    $grandchild"
        }
    }
}
puts "=================================="

# ============================================================================
# Memory Banking Directives
# ============================================================================
# Force SRAM mapping to prevent 'memories' pass exploration.
# Path is auto-detected from design hierarchy after go analyze.
# ============================================================================

set top_path ""
foreach child [solution design get -child /] {
    if {[string match "*StemProcessor*" $child] || [string match "*run*" $child]} {
        set top_path $child
        puts "Found top path: $top_path"
        break
    }
}

if {$top_path eq ""} {
    puts "WARNING: Could not auto-detect top path. Listing all design elements:"
    catch {
        foreach item [solution design get -child / -rec] {
            puts "  $item"
        }
    }
    puts "Skipping memory directives - check hierarchy paths in log"
    go compile
} else {
    puts "Applying memory directives with prefix: $top_path"
    set directive_errors 0

    # All buffers are class members in V2
    foreach {varpath desc} {
        line_buf_a.buffer   "Conv0 input (160KB)"
        line_buf_b.buffer   "Conv0 output (160KB)"
        conv1_buf.buffer    "Conv1 output (160KB)"
        mp_buf.buffer       "MaxPool buffer (160KB)"
        concat_buf.path_a   "Concat path A (20KB)"
        concat_buf.path_b   "Concat path B (20KB)"
    } {
        set full_path "${top_path}/${varpath}:rsc"
        puts "  Trying: directive set $full_path -MAP_TO_MODULE BLOCK_1R1W_RBW  ($desc)"
        if {[catch {directive set $full_path -MAP_TO_MODULE {BLOCK_1R1W_RBW}} err]} {
            puts "  FAILED: $err"
            incr directive_errors
        }
    }

    if {$directive_errors > 0} {
        puts "WARNING: $directive_errors directive(s) failed. Check paths above."
    } else {
        puts "All memory directives applied successfully."
    }

    go compile
}

# Optional: generate SCVerify build/run scripts
flow package require /SCVerify

# Generate .ccs launcher
set ccs_fd [open ./stem_v2_processor.ccs w]
puts $ccs_fd {// Auto-generated by run_stem_v2_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain stem_v2_processor*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'stem_v2_processor*'}
  }
}}
close $ccs_fd

exit
