# Catapult batch script for FusedBlockProcessor
# Run example:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_block_processor_catapult.tcl

project new -name block_processor

# Start from a clean solution state
solution new -state initial
solution options defaults

# Useful default flow options
solution options set /Flows/Enable-SCVerify yes
solution options set /Output/GenerateCycleNetlist false

# Design + testbench files
solution file add ./src/streaming/block_processor.cpp -type C++
solution file add ./src/streaming/block_processor_tb.cpp -type C++ -exclude true

# Analyze/compile
go analyze
go compile

# Optional: generate SCVerify build/run scripts
flow package require /SCVerify

# Generate .ccs launcher so GUI can reopen project
set ccs_fd [open ./block_processor.ccs w]
puts $ccs_fd {// Auto-generated by run_block_processor_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain block_processor*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'block_processor*'}
  }
}}
close $ccs_fd

exit
