# Catapult batch script for GPTBackbonePhase3
# Run:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_gpt_backbone_phase3_catapult.tcl

project new -name gpt_backbone_phase3

solution new -state initial
solution options defaults
solution options set /Output/GenerateCycleNetlist false

solution file add ./src/GPT_src/gpt_backbone_phase3.cpp -type C++
solution file add ./src/GPT_src/gpt_backbone_phase3_tb.cpp -type C++ -exclude true

go analyze

if {[catch {directive set -CLOCK_OVERHEAD 0} err]} {
  puts "CLOCK_OVERHEAD set failed: $err"
} else {
  puts "CLOCK_OVERHEAD set to 0"
}

if {[catch {directive set -MEM_MAP_THRESHOLD 8192} err]} {
  puts "MEM_MAP_THRESHOLD set failed: $err"
} else {
  puts "MEM_MAP_THRESHOLD set to 8192"
}

go compile

# Generate .ccs launcher
set ccs_fd [open ./gpt_backbone_phase3.ccs w]
puts $ccs_fd {// Auto-generated by run_gpt_backbone_phase3_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain gpt_backbone_phase3*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'gpt_backbone_phase3*'}
  }
}}
close $ccs_fd

if {![info exists KEEP_GUI_OPEN] || !$KEEP_GUI_OPEN} {
  exit
}
