# Catapult batch script for StemProcessor V2 (tile-optimized)
# Run example:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_stem_v2_catapult.tcl

project new -name stem_v2_processor

# Start from a clean solution state
solution new -state initial
solution options defaults

# Useful default flow options
solution options set /Flows/Enable-SCVerify yes
solution options set /Output/GenerateCycleNetlist false

# Design + testbench files
solution file add ./src/stem_v2/stem_v2_processor.cpp -type C++
solution file add ./src/stem_v2/stem_v2_processor_tb.cpp -type C++ -exclude true

# Analyze
go analyze

# ============================================================================
# Memory Banking Directives
# ============================================================================
#
# Force SRAM mapping for all line buffers.
# This prevents the 'memories' pass from exploring all possible
# banking/port configurations, which caused 10+ hour synthesis hangs in V1.
#
# BLOCK_1R1W_RBW = Single-port RAM with 1 read + 1 write per cycle
# (Read-Before-Write behavior)
#
# Without these directives, Catapult tries every possible configuration:
#   - Register vs RAM
#   - 1-port vs 2-port vs multi-port
#   - Banking factor 1, 2, 4, 8, ...
#   - Channel-dim vs col-dim vs row-dim banking
#   = thousands of combinations per buffer x 4 buffers = explosion
#
# With directives: Catapult uses the specified mapping directly.
# ============================================================================

# Line Buffer A: Conv0 input (RGB window buffer)
# [4][640][64] x 8bit = 160KB
directive set /StemProcessor/line_buf_a.buffer:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}

# Line Buffer B: Conv0 output (Conv1 input)
# [4][640][64] x 8bit = 160KB
directive set /StemProcessor/line_buf_b.buffer:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}

# Conv1 Buffer: Conv1 output (Conv2 input)
# [4][640][64] x 8bit = 160KB
directive set /StemProcessor/conv1_buf.buffer:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}

# MaxPool Buffer: Conv0 output copy for MaxPool
# [4][640][64] x 8bit = 160KB
directive set /StemProcessor/mp_buf.buffer:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}

# Concat Buffer Path A
# [640][32] x 8bit = 20KB
directive set /StemProcessor/concat_buf.path_a:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}

# Concat Buffer Path B
# [640][32] x 8bit = 20KB
directive set /StemProcessor/concat_buf.path_b:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}

# ============================================================================
# Compile with directives applied
# ============================================================================

go compile

# Optional: generate SCVerify build/run scripts
flow package require /SCVerify

# Generate .ccs launcher
set ccs_fd [open ./stem_v2_processor.ccs w]
puts $ccs_fd {// Auto-generated by run_stem_v2_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain stem_v2_processor*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'stem_v2_processor*'}
  }
}}
close $ccs_fd

exit
