# Catapult batch script for StemProcessor
# Run example:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_stem_catapult.tcl

project new -name stem_processor

# Start from a clean solution state
solution new -state initial
solution options defaults

# Useful default flow options
solution options set /Flows/Enable-SCVerify yes
solution options set /Output/GenerateCycleNetlist false

# Design + testbench files
solution file add ./src/stem/stem_processor.cpp -type C++
solution file add ./src/stem/stem_processor_tb.cpp -type C++ -exclude true

# Analyze
go analyze

# ============================================================================
# Discover Design Hierarchy
# ============================================================================
puts "======== DESIGN HIERARCHY DEBUG ========"
catch {puts "solution design get: [solution design get]"}
catch {puts "directive get -rec: [directive get -rec]"}
puts "========================================"

# ============================================================================
# Memory Banking Directives
# ============================================================================
# Force SRAM mapping to prevent 'memories' pass exploration.
# Try multiple path formats since naming depends on Catapult version.
# ============================================================================

# Buffer paths to set (member.array suffix)
set member_buffers {
    line_buf_a.buffer
    line_buf_b.buffer
    concat_buf.path_a
    concat_buf.path_b
}
set local_buffers {
    run/conv1_buf.buffer
    run/mp_buf.buffer
}

# Possible top-level path prefixes (try each until one works)
set path_prefixes {
    /StemProcessor
    /StemProcessor/run
    /stem_processor/StemProcessor
    /stem_processor/StemProcessor/run
}

set applied 0
foreach prefix $path_prefixes {
    set test_path "${prefix}/line_buf_a.buffer:rsc"
    puts "Testing prefix: $prefix ..."
    if {![catch {directive set $test_path -MAP_TO_MODULE {BLOCK_1R1W_RBW}}]} {
        puts "  SUCCESS - using prefix: $prefix"
        set applied 1
        # Apply remaining member buffers (skip line_buf_a, already done)
        foreach buf {line_buf_b.buffer concat_buf.path_a concat_buf.path_b} {
            catch {directive set ${prefix}/${buf}:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}} err
            puts "  ${prefix}/${buf}:rsc -> $err"
        }
        # Apply local buffers (V1 has conv1_buf and mp_buf as locals in run())
        foreach buf $local_buffers {
            catch {directive set ${prefix}/${buf}:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}} err
            puts "  ${prefix}/${buf}:rsc -> $err"
        }
        break
    } else {
        puts "  FAILED"
    }
}

if {!$applied} {
    puts "WARNING: No valid path prefix found. Proceeding without memory directives."
    puts "Check 'DESIGN HIERARCHY DEBUG' section above for available paths."
}

go compile

# Optional: generate SCVerify build/run scripts
flow package require /SCVerify

# Generate .ccs launcher so GUI can reopen project
set ccs_fd [open ./stem_processor.ccs w]
puts $ccs_fd {// Auto-generated by run_stem_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain stem_processor*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'stem_processor*'}
  }
}}
close $ccs_fd

exit
