# Catapult batch script for StemProcessor V2 (tile-optimized)
# Run example:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_stem_v2_catapult.tcl

project new -name stem_v2_processor

# Start from a clean solution state
solution new -state initial
solution options defaults

# Useful default flow options
solution options set /Flows/Enable-SCVerify yes
solution options set /Output/GenerateCycleNetlist false

# Design + testbench files
solution file add ./src/stem_v2/stem_v2_processor.cpp -type C++
solution file add ./src/stem_v2/stem_v2_processor_tb.cpp -type C++ -exclude true

# Analyze
go analyze

# ============================================================================
# Discover Design Hierarchy
# ============================================================================
puts "======== DESIGN HIERARCHY DEBUG ========"
catch {puts "solution design get: [solution design get]"}
catch {puts "directive get -rec: [directive get -rec]"}
puts "========================================"

# ============================================================================
# Memory Banking Directives
# ============================================================================
# Force SRAM mapping to prevent 'memories' pass exploration.
# Try multiple path formats since naming depends on Catapult version.
# ============================================================================

# All buffers are class members in V2
set v2_buffers {
    line_buf_a.buffer
    line_buf_b.buffer
    conv1_buf.buffer
    mp_buf.buffer
    concat_buf.path_a
    concat_buf.path_b
}

# Possible top-level path prefixes
set path_prefixes {
    /StemProcessor
    /StemProcessor/run
    /stem_v2_processor/StemProcessor
    /stem_v2_processor/StemProcessor/run
}

set applied 0
foreach prefix $path_prefixes {
    set test_path "${prefix}/line_buf_a.buffer:rsc"
    puts "Testing prefix: $prefix ..."
    if {![catch {directive set $test_path -MAP_TO_MODULE {BLOCK_1R1W_RBW}}]} {
        puts "  SUCCESS - using prefix: $prefix"
        set applied 1
        # Apply remaining buffers (skip line_buf_a, already done)
        foreach buf {line_buf_b.buffer conv1_buf.buffer mp_buf.buffer concat_buf.path_a concat_buf.path_b} {
            catch {directive set ${prefix}/${buf}:rsc -MAP_TO_MODULE {BLOCK_1R1W_RBW}} err
            puts "  ${prefix}/${buf}:rsc -> $err"
        }
        break
    } else {
        puts "  FAILED"
    }
}

if {!$applied} {
    puts "WARNING: No valid path prefix found. Proceeding without memory directives."
    puts "Check 'DESIGN HIERARCHY DEBUG' section above for available paths."
}

go compile

# Optional: generate SCVerify build/run scripts
flow package require /SCVerify

# Generate .ccs launcher
set ccs_fd [open ./stem_v2_processor.ccs w]
puts $ccs_fd {// Auto-generated by run_stem_v2_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain stem_v2_processor*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'stem_v2_processor*'}
  }
}}
close $ccs_fd

exit
