# Catapult batch script for StemProcessor
# Run example:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_stem_catapult.tcl

project new -name stem_processor

# Start from a clean solution state
solution new -state initial
solution options defaults

# Useful default flow options
solution options set /Flows/Enable-SCVerify yes
solution options set /Output/GenerateCycleNetlist false

# Design + testbench files
solution file add ./src/stem/stem_processor.cpp -type C++
solution file add ./src/stem/stem_processor_tb.cpp -type C++ -exclude true

# Analyze
go analyze

# ============================================================================
# Discover Design Hierarchy
# ============================================================================
puts "======== DESIGN HIERARCHY DEBUG ========"
catch {puts "solution design get: [solution design get]"}
catch {puts "directive get -rec: [directive get -rec]"}
puts "========================================"

# ============================================================================
# Memory Banking Directives
# ============================================================================
# Force SRAM mapping to prevent 'memories' pass exploration.
# Try multiple path formats since naming depends on Catapult version.
# ============================================================================

proc map_buffer_resource {label keys roots} {
    foreach root $roots {
        foreach key $keys {
            set path "${root}/${key}:rsc"
            if {![catch {directive set $path -MAP_TO_MODULE {BLOCK_1R1W_RBW}} err]} {
                puts "MAP OK  : ${label} -> ${path}"
                return 1
            }
        }
    }
    puts "MAP FAIL: ${label}"
    return 0
}

# Build candidate roots from discovered design names + known fallbacks.
set roots {
    /StemProcessor
    /StemProcessor/run
    /stem_processor/StemProcessor
    /stem_processor/StemProcessor/run
}
set design_names {}
catch {set design_names [solution design get]}
foreach d $design_names {
    if {[string first "::" $d] >= 0} { continue }
    lappend roots "/$d"
    lappend roots "/$d/run"
}
set roots [lsort -unique $roots]
puts "Memory mapping roots: $roots"

set map_total 0
set map_ok 0

incr map_total
if {[map_buffer_resource "line_buf_a.buffer" {line_buf_a.buffer line_buf_a/buffer} $roots]} { incr map_ok }
incr map_total
if {[map_buffer_resource "line_buf_b.buffer" {line_buf_b.buffer line_buf_b/buffer} $roots]} { incr map_ok }
incr map_total
if {[map_buffer_resource "conv1_buf.buffer" {conv1_buf.buffer conv1_buf/buffer run/conv1_buf.buffer run/conv1_buf/buffer} $roots]} { incr map_ok }
incr map_total
if {[map_buffer_resource "mp_buf.buffer" {mp_buf.buffer mp_buf/buffer run/mp_buf.buffer run/mp_buf/buffer} $roots]} { incr map_ok }
incr map_total
if {[map_buffer_resource "concat_buf.path_a" {concat_buf.path_a concat_buf/path_a} $roots]} { incr map_ok }
incr map_total
if {[map_buffer_resource "concat_buf.path_b" {concat_buf.path_b concat_buf/path_b} $roots]} { incr map_ok }

puts "Memory directive mapping summary: ${map_ok}/${map_total} resources mapped."

# Keep clock overhead explicit to avoid SCHD-22 style schedule blockers.
if {[catch {directive set -CLOCK_OVERHEAD 0} clk_err]} {
    puts "CLOCK_OVERHEAD set failed: $clk_err"
} else {
    puts "CLOCK_OVERHEAD set to 0"
}

go compile

# Archive key reports so timing/schedule changes are traceable across runs.
set report_dir ./logs/reports
catch {file mkdir ./logs}
catch {file mkdir $report_dir}
set sols [lsort -dictionary [glob -nocomplain ./stem_processor/StemProcessor.v* ./stem_processor/solution.v*]]
if {[llength $sols] > 0} {
    set sol [lindex $sols end]
    foreach f {messages.txt schedule.txt schedule.rpt architect.rpt compile.rpt} {
        set src "${sol}/${f}"
        if {[file exists $src]} {
            set dst "${report_dir}/stem_${f}"
            catch {file copy -force $src $dst}
            puts "Archived report: $src -> $dst"
        }
    }
}

# Optional: generate SCVerify build/run scripts
flow package require /SCVerify

# Generate .ccs launcher so GUI can reopen project
set ccs_fd [open ./stem_processor.ccs w]
puts $ccs_fd {// Auto-generated by run_stem_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain stem_processor*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'stem_processor*'}
  }
}}
close $ccs_fd

if {![info exists KEEP_GUI_OPEN] || !$KEEP_GUI_OPEN} {
  exit
}
