# Catapult batch script for BW_CNN_Streaming
# Run example:
#   cd Binary_cnn
#   catapult -shell -file scripts/run_streaming_catapult.tcl

project new -name bin_cnn_streaming

# Start from a clean solution state
solution new -state initial
solution options defaults

# Useful default flow options
solution options set /Flows/Enable-SCVerify yes
solution options set /Output/GenerateCycleNetlist false

# Design + testbench files (TB excluded from synthesis)
solution file add ./src/streaming/bw_cnn_streaming.h -type C++
solution file add ./src/streaming/block_config.h -type C++
solution file add ./src/streaming/tile_manager.h -type C++
solution file add ./src/streaming/inter_layer_buffer.h -type C++
solution file add ./src/streaming/bw_cnn_streaming.cpp -type C++
solution file add ./src/streaming/bw_cnn_streaming_tb.cpp -type C++ -exclude true

# Analyze/compile
go analyze
go compile

# Optional: generate SCVerify build/run scripts
flow package require /SCVerify

# Write a launcher file so GUI can reopen the latest streaming project easily.
set ccs_fd [open ./bin_cnn_streaming.ccs w]
puts $ccs_fd {// Auto-generated by run_streaming_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain bin_cnn_streaming*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'bin_cnn_streaming*'}
  }
}}
close $ccs_fd

exit
