# ----------------------------------------------------------------------------
# RTL Verilog output 'rtl.v' vs Untimed C++
#
#    HLS version: 2025.2_1/1197638 Production Release
#       HLS date: Thu Jun 12 00:48:01 PDT 2025
#  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
#
#   Generated by: soc_lab_LMJ@ssu_soc_lab
# Generated date: Thu Feb 19 18:20:17 KST 2026
#
# ----------------------------------------------------------------------------
# ===================================================
# DEFAULT GOAL is the help target
.PHONY: all
all: help

# ===================================================
# Directories (at the time this makefile was created)
#   MGC_HOME      /usr/local/bin/Siemens_EDA/Catapult_Synthesis_2025.2_1-1197638/Mgc_home
#   PROJECT_HOME  /mnt/HDD/soc_lab_LMJ/catapultwork/git/HLS/Binary_cnn
#   SOLUTION_DIR  /mnt/HDD/soc_lab_LMJ/catapultwork/git/HLS/Binary_cnn/gpt_backbone_phase3/GPTBackbonePhase3.v1
#   WORKING_DIR   /mnt/HDD/soc_lab_LMJ/catapultwork/git/HLS/Binary_cnn/gpt_backbone_phase3/GPTBackbonePhase3.v1/.

# ===================================================
# VARIABLES
# 
MGC_HOME          = /usr/local/bin/Siemens_EDA/Catapult_Synthesis_2025.2_1-1197638/Mgc_home
export MGC_HOME

WORK_DIR  = $(CURDIR)
WORK2PROJ = ../..
WORK2SOLN = .
PROJ2WORK = ./gpt_backbone_phase3/GPTBackbonePhase3.v1
PROJ2SOLN = ./gpt_backbone_phase3/GPTBackbonePhase3.v1
export WORK_DIR
export WORK2PROJ
export WORK2SOLN
export PROJ2WORK
export PROJ2SOLN

# Variables that can be overridden from the make command line
ifeq "$(INCL_DIRS)" ""
INCL_DIRS                   = ./scverify . ../..
endif
export INCL_DIRS
ifeq "$(STAGE)" ""
STAGE                       = rtl
endif
export STAGE
ifeq "$(NETLIST_LEAF)" ""
NETLIST_LEAF                = rtl
endif
export NETLIST_LEAF
ifeq "$(SIMTOOL)" ""
SIMTOOL                     = msim
endif
export SIMTOOL
ifeq "$(NETLIST)" ""
NETLIST                     = v
endif
export NETLIST
ifeq "$(RTL_NETLIST_FNAME)" ""
RTL_NETLIST_FNAME           = /mnt/HDD/soc_lab_LMJ/catapultwork/git/HLS/Binary_cnn/gpt_backbone_phase3/GPTBackbonePhase3.v1/rtl.v
endif
export RTL_NETLIST_FNAME
ifeq "$(INVOKE_ARGS)" ""
INVOKE_ARGS                 = 
endif
export INVOKE_ARGS
ifeq "$(FAMILY)" ""
FAMILY                      = zynq-uplus
endif
export FAMILY
export SCVLIBS
export MODELSIM
TOP_HDL_ENTITY           := GPTBackbonePhase3
TOP_DU                   := scverify_top
CXX_TYPE                 := gcc
MSIM_SCRIPT              := ./gpt_backbone_phase3/GPTBackbonePhase3.v1/scverify_msim.tcl
TARGET                   := scverify/$(NETLIST_LEAF)_$(NETLIST)_$(SIMTOOL)
export TOP_HDL_ENTITY
export TARGET

ifeq ($(RECUR),)
ifeq ($(STAGE),mapped)
ifeq ($(RTLTOOL),)
   $(error This makefile requires specifying the RTLTOOL variable on the make command line)
endif
endif
endif
# ===================================================
# Include environment variables set by flow options
include ./ccs_env.mk

# ===================================================
# Include makefile for default commands and variables
include $(MGC_HOME)/shared/include/mkfiles/ccs_default_cmds.mk

SYNTHESIS_FLOWPKG := Vivado
SYN_FLOW          := Vivado
# ===================================================
# SOURCES
# 
# Specify list of Questa SIM libraries to create
HDL_LIB_NAMES = mgc_hls work
# ===================================================
# Simulation libraries required by loaded Catapult libraries or gate simulation
SIMLIBS_V   += 
SIMLIBS_VHD += 
# 
# 
# Specify list of source files - MUST be ordered properly
ifeq ($(STAGE),gate)
ifeq ($(RTLTOOL),)
# Unless overridden on make command line, GATE_*_DEP is the last item in the netlist dependency list
ifeq ($(GATE_VHDL_DEP),)
GATE_VHDL_DEP = 
endif
ifeq ($(GATE_VLOG_DEP),)
GATE_VLOG_DEP = ./rtl.v/rtl.v.vts
endif
endif
VHDL_SRC +=  $(GATE_VHDL_DEP) 
VLOG_SRC += $(MGC_HOME)/pkgs/siflibs/ccs_ctrl_in_buf_wait_v4.v/ccs_ctrl_in_buf_wait_v4.v.vts $(MGC_HOME)/pkgs/siflibs/ccs_out_buf_wait_v5.v/ccs_out_buf_wait_v5.v.vts $(MGC_HOME)/pkgs/siflibs/mgc_shift_l_beh_v5.v/mgc_shift_l_beh_v5.v.vts $(MGC_HOME)/pkgs/siflibs/mgc_shift_r_beh_v5.v/mgc_shift_r_beh_v5.v.vts $(MGC_HOME)/pkgs/ccs_xilinx/hdl/BLOCK_1R1W_RBW.v/BLOCK_1R1W_RBW.v.vts $(GATE_VLOG_DEP) ./scverify/ccs_wrapper_GPTBackbonePhase3.v/ccs_wrapper_GPTBackbonePhase3.v.vts
else
VHDL_SRC += 
VLOG_SRC += $(MGC_HOME)/pkgs/siflibs/ccs_ctrl_in_buf_wait_v4.v/ccs_ctrl_in_buf_wait_v4.v.vts $(MGC_HOME)/pkgs/siflibs/ccs_out_buf_wait_v5.v/ccs_out_buf_wait_v5.v.vts $(MGC_HOME)/pkgs/siflibs/mgc_shift_l_beh_v5.v/mgc_shift_l_beh_v5.v.vts $(MGC_HOME)/pkgs/siflibs/mgc_shift_r_beh_v5.v/mgc_shift_r_beh_v5.v.vts $(MGC_HOME)/pkgs/ccs_xilinx/hdl/BLOCK_1R1W_RBW.v/BLOCK_1R1W_RBW.v.vts ./rtl.v/rtl.v.vts ./scverify/ccs_wrapper_GPTBackbonePhase3.v/ccs_wrapper_GPTBackbonePhase3.v.vts
endif
CXX_SRC  = ../../src/GPT_src/gpt_backbone_phase3.cpp/gpt_backbone_phase3.cpp.cxxts ../../src/GPT_src/gpt_backbone_phase3_tb.cpp/gpt_backbone_phase3_tb.cpp.cxxts ./scverify/mc_testbench.cpp/mc_testbench.cpp.cxxts ./scverify/scverify_top.cpp/scverify_top.cpp.cxxts
# Specify RTL synthesis scripts (if any)
RTL_SCRIPT = 

# Specify hold time file name (for verifying synthesized netlists)
HLD_CONSTRAINT_FNAME = top_gate_constraints.cpp

# ===================================================
# GLOBAL OPTIONS
# 
# CXXFLAGS - global C++ options (apply to all C++ compilations) except for include file search paths
CXXFLAGS += $(COMPILERFLAGS) -DCCS_SCVERIFY -DSC_INCLUDE_DYNAMIC_PROCESSES -DSC_USE_STD_STRING -DTOP_HDL_ENTITY=$(TOP_HDL_ENTITY) -DCCS_DESIGN_FUNC_GPTBackbonePhase3_run -DCCS_DESIGN_TOP_$(TOP_HDL_ENTITY) -DCCS_MISMATCHED_OUTPUTS_ONLY $(F_WRAP_OPT)
# 
# If the make command line includes a definition of the special variable MC_DEFAULT_TRANSACTOR_LOG
# then define that value for all compilations as well
ifneq "$(MC_DEFAULT_TRANSACTOR_LOG)" ""
CXXFLAGS += -DMC_DEFAULT_TRANSACTOR_LOG=$(MC_DEFAULT_TRANSACTOR_LOG)
endif
# 
# CXX_INCLUDES - include file search paths
CXX_INCLUDES = ./scverify . ../..
# 
# TCL shell
TCLSH_CMD = /usr/local/bin/Siemens_EDA/Catapult_Synthesis_2025.2_1-1197638/Mgc_home/bin/tclsh8.5

# Pass along SCVerify_DEADLOCK_DETECTION option
ifneq "$(SCVerify_DEADLOCK_DETECTION)" "false"
CXXFLAGS += -DDEADLOCK_DETECTION
endif
# ===================================================
# PER SOURCE FILE SPECIALIZATIONS
# 
# Specify source file paths
ifeq ($(STAGE),gate)
ifneq ($(GATE_VHDL_DEP),)
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): $(dir $(GATE_VHDL_DEP))
endif
ifneq ($(GATE_VLOG_DEP),)
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): $(dir $(GATE_VLOG_DEP))
endif
endif
$(TARGET)/ccs_ctrl_in_buf_wait_v4.v.vts: $(MGC_HOME)/pkgs/siflibs/ccs_ctrl_in_buf_wait_v4.v
$(TARGET)/ccs_out_buf_wait_v5.v.vts: $(MGC_HOME)/pkgs/siflibs/ccs_out_buf_wait_v5.v
$(TARGET)/mgc_shift_l_beh_v5.v.vts: $(MGC_HOME)/pkgs/siflibs/mgc_shift_l_beh_v5.v
$(TARGET)/mgc_shift_r_beh_v5.v.vts: $(MGC_HOME)/pkgs/siflibs/mgc_shift_r_beh_v5.v
$(TARGET)/BLOCK_1R1W_RBW.v.vts: $(MGC_HOME)/pkgs/ccs_xilinx/hdl/BLOCK_1R1W_RBW.v
$(TARGET)/rtl.v.vts: ./rtl.v
$(TARGET)/ccs_wrapper_GPTBackbonePhase3.v.vts: ./scverify/ccs_wrapper_GPTBackbonePhase3.v
$(TARGET)/gpt_backbone_phase3.cpp.cxxts: ../../src/GPT_src/gpt_backbone_phase3.cpp
$(TARGET)/gpt_backbone_phase3_tb.cpp.cxxts: ../../src/GPT_src/gpt_backbone_phase3_tb.cpp
$(TARGET)/mc_testbench.cpp.cxxts: ./scverify/mc_testbench.cpp
$(TARGET)/scverify_top.cpp.cxxts: ./scverify/scverify_top.cpp
# 
# Specify additional C++ options per C++ source by setting CXX_OPTS
$(TARGET)/gpt_backbone_phase3_tb.cpp.cxxts: CXX_OPTS=
$(TARGET)/scverify_top.cpp.cxxts: CXX_OPTS=
$(TARGET)/mc_testbench.cpp.cxxts: CXX_OPTS=$(F_WRAP_OPT)
$(TARGET)/gpt_backbone_phase3.cpp.cxxts: CXX_OPTS=
# 
# Specify dependencies
$(TARGET)/gpt_backbone_phase3.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/gpt_backbone_phase3_tb.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/mc_testbench.cpp.cxxts: ./scverify/mc_testbench.h ./scverify/ccs_testbench.h ./scverify/ccs_block_macros.h ./scverify/ccs_block_macros.cpp .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/scverify_top.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts ./scverify/ccs_probes.h .ccs_env_opts/SCVerify_DEADLOCK_DETECTION.ts
# 
# Specify compilation library for HDL source
$(TARGET)/ccs_out_buf_wait_v5.v.vts: HDL_LIB=mgc_hls
$(TARGET)/ccs_ctrl_in_buf_wait_v4.v.vts: HDL_LIB=mgc_hls
$(TARGET)/ccs_wrapper_GPTBackbonePhase3.v.vts: HDL_LIB=work
$(TARGET)/BLOCK_1R1W_RBW.v.vts: HDL_LIB=mgc_hls
$(TARGET)/mgc_shift_r_beh_v5.v.vts: HDL_LIB=mgc_hls
$(TARGET)/mgc_shift_l_beh_v5.v.vts: HDL_LIB=mgc_hls
$(TARGET)/rtl.v.vts: HDL_LIB=work
ifeq ($(STAGE),gate)
ifneq ($(GATE_VHDL_DEP),)
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): HDL_LIB=work
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): DUT_E=mgc_shift_l_v5
endif
ifneq ($(GATE_VLOG_DEP),)
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): HDL_LIB=work
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): DUT_E=mgc_shift_l_v5
endif
endif
# 
# Specify additional HDL source compilation options if any
$(TARGET)/ccs_out_buf_wait_v5.v.vts: VLOG_F_OPTS=
$(TARGET)/ccs_ctrl_in_buf_wait_v4.v.vts: VLOG_F_OPTS=
$(TARGET)/ccs_wrapper_GPTBackbonePhase3.v.vts: VLOG_F_OPTS=
$(TARGET)/BLOCK_1R1W_RBW.v.vts: VLOG_F_OPTS=
$(TARGET)/mgc_shift_r_beh_v5.v.vts: VLOG_F_OPTS=
$(TARGET)/mgc_shift_l_beh_v5.v.vts: VLOG_F_OPTS=
$(TARGET)/rtl.v.vts: VLOG_F_OPTS=
$(TARGET)/ccs_out_buf_wait_v5.v.vts: NCVLOG_F_OPTS=
$(TARGET)/ccs_ctrl_in_buf_wait_v4.v.vts: NCVLOG_F_OPTS=
$(TARGET)/ccs_wrapper_GPTBackbonePhase3.v.vts: NCVLOG_F_OPTS=
$(TARGET)/BLOCK_1R1W_RBW.v.vts: NCVLOG_F_OPTS=
$(TARGET)/mgc_shift_r_beh_v5.v.vts: NCVLOG_F_OPTS=
$(TARGET)/mgc_shift_l_beh_v5.v.vts: NCVLOG_F_OPTS=
$(TARGET)/rtl.v.vts: NCVLOG_F_OPTS=
$(TARGET)/ccs_out_buf_wait_v5.v.vts: VCS_F_OPTS=
$(TARGET)/ccs_ctrl_in_buf_wait_v4.v.vts: VCS_F_OPTS=
$(TARGET)/ccs_wrapper_GPTBackbonePhase3.v.vts: VCS_F_OPTS=
$(TARGET)/BLOCK_1R1W_RBW.v.vts: VCS_F_OPTS=
$(TARGET)/mgc_shift_r_beh_v5.v.vts: VCS_F_OPTS=
$(TARGET)/mgc_shift_l_beh_v5.v.vts: VCS_F_OPTS=
$(TARGET)/rtl.v.vts: VCS_F_OPTS=
# 
# Specify top design unit for HDL source
$(TARGET)/ccs_out_buf_wait_v5.v.vts: DUT_E=ccs_out_buf_wait_v5
$(TARGET)/ccs_ctrl_in_buf_wait_v4.v.vts: DUT_E=ccs_ctrl_in_buf_wait_v4
$(TARGET)/ccs_wrapper_GPTBackbonePhase3.v.vts: DUT_E=ccs_wrapper
$(TARGET)/BLOCK_1R1W_RBW.v.vts: DUT_E=BLOCK_1R1W_RBW
$(TARGET)/mgc_shift_r_beh_v5.v.vts: DUT_E=mgc_shift_r_v5
$(TARGET)/mgc_shift_l_beh_v5.v.vts: DUT_E=mgc_shift_l_v5
$(TARGET)/rtl.v.vts: DUT_E=GPTBackbonePhase3

# Specify top design unit
$(TARGET)/ccs_wrapper_GPTBackbonePhase3.v.vts: VLOG_TOP=1

ifneq "$(RTLTOOL)" ""
# ===================================================
# Include makefile for RTL synthesis
include $(MGC_HOME)/shared/include/mkfiles/ccs_$(RTLTOOL).mk
else
# ===================================================
# Include makefile for simulator
include $(MGC_HOME)/shared/include/mkfiles/ccs_questasim.mk
endif

