# Catapult batch script for PEParallelBlock
# Run:
#   cd PE
#   catapult -shell -file scripts/run_pe_catapult.tcl

project new -name PE

solution new -state initial
solution options defaults
solution options set /Output/GenerateCycleNetlist false

solution file add ./include/pe_types.h          -type C++
solution file add ./include/pe_packets.h        -type C++
solution file add ./include/pe_config.h         -type C++
solution file add ./src/pe_unit.h               -type C++
solution file add ./src/pe_unit.cpp             -type C++
solution file add ./src/pe_parallel_block.h     -type C++
solution file add ./src/pe_parallel_block.cpp   -type C++

solution file add ./tb/pe_reference_model.h     -type C++ -exclude true
solution file add ./tb/pe_parallel_block_tb.cpp -type C++ -exclude true

go analyze

if {[catch {directive set -MEM_MAP_THRESHOLD 8192} err]} {
    puts "MEM_MAP_THRESHOLD failed: $err"
} else {
    puts "MEM_MAP_THRESHOLD = 8192"
}

if {[catch {directive set -CLOCK_OVERHEAD 0} err]} {
    puts "CLOCK_OVERHEAD failed: $err"
} else {
    puts "CLOCK_OVERHEAD = 0"
}

set compile_only 0
if {[info exists ::env(PE_COMPILE_ONLY)]} {
    set v $::env(PE_COMPILE_ONLY)
    if {$v ne "" && $v ne "0"} {
        set compile_only 1
    }
}

set analyze_only 0
if {[info exists ::env(PE_ANALYZE_ONLY)]} {
    set v $::env(PE_ANALYZE_ONLY)
    if {$v ne "" && $v ne "0"} {
        set analyze_only 1
    }
}

if {$analyze_only} {
    puts "PE_ANALYZE_ONLY enabled: stopping after analyze"

    set ccs_fd [open ./PE.ccs w]
    puts $ccs_fd {// Auto-generated by run_pe_catapult.tcl}
    puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain PE*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'PE*'}
  }
}}
    close $ccs_fd
    exit
}

go compile
if {!$compile_only} {
    go architect
    go schedule
    go extract
} else {
    puts "PE_COMPILE_ONLY enabled: skipping architect/schedule/extract"
}

set ccs_fd [open ./PE.ccs w]
puts $ccs_fd {// Auto-generated by run_pe_catapult.tcl}
puts $ccs_fd {if {[info script] != {} && [file isdirectory [file rootname [info script]]]} {
  project load [file rootname [info script]] 2025.2
} else {
  set _dirs [lsort -dictionary [glob -nocomplain PE*]]
  set _proj {}
  foreach d $_dirs { if {[file isdirectory $d]} { set _proj $d } }
  if {$_proj ne {}} {
    project load $_proj 2025.2
  } else {
    error {unable to locate project directory 'PE*'}
  }
}}
close $ccs_fd

if {![info exists KEEP_GUI_OPEN] || !$KEEP_GUI_OPEN} {
    exit
}
